language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-fluid' ]; then cd .. && eval "mv $currentfolder generator-fluid" && cd generator-fluid; fi

