<?php
return array(
	'BE' => array(
		'debug' => '',
		'installToolPassword' => '$P$CBYKlbCn9bDalli5Y17Iwci22yPjES/',
		'loginSecurityLevel' => 'normal',
	),
	'DB' => array(
		'database' => 'db',
		'extTablesDefinitionScript' => 'extTables.php',
		'host' => '127.0.0.1',
		'password' => '',
		'port' => 3306,
		'username' => '',
	),
	'EXT' => array(
		'extConf' => array(
			'extbase' => 'a:0:{}',
			'extension_builder' => 'a:3:{s:15:"enableRoundtrip";s:0:"";s:15:"backupExtension";s:1:"1";s:9:"backupDir";s:35:"uploads/tx_extensionbuilder/backups";}',
			'feedit' => 'a:0:{}',
			'fluid' => 'a:0:{}',
			'fluidcontent' => 'a:1:{s:9:"removeTab";s:1:"1";}',
			'fluidpages' => 'a:2:{s:8:"doktypes";s:0:"";s:10:"autoRender";s:1:"0";}',
			'fluidwidget' => 'a:0:{}',
			'flux' => 'a:5:{s:9:"debugMode";s:1:"0";s:15:"disableCompiler";s:1:"0";s:7:"compact";s:1:"0";s:12:"handleErrors";s:1:"0";s:20:"rewriteLanguageFiles";s:1:"0";}',
			'opendocs' => 'a:0:{}',
			'phpmyadmin' => 'a:5:{s:12:"hideOtherDBs";s:1:"1";s:9:"uploadDir";s:21:"uploads/tx_phpmyadmin";s:10:"allowedIps";s:0:"";s:12:"useDevIpMask";s:1:"0";s:10:"ajaxEnable";s:1:"1";}',
			'phpunit' => 'a:6:{s:17:"excludeextensions";s:8:"lib, div";s:12:"composerpath";s:0:"";s:13:"selenium_host";s:9:"localhost";s:13:"selenium_port";s:4:"4444";s:16:"selenium_browser";s:8:"*firefox";s:19:"selenium_browserurl";s:0:"";}',
			'pt_extbase' => 'a:0:{}',
			'realurl' => 'a:5:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
			'recycler' => 'a:0:{}',
			'saltedpasswords' => 'a:2:{s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}s:3:"FE.";a:5:{s:7:"enabled";i:0;s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}}',
			'scheduler' => 'a:4:{s:11:"maxLifetime";s:4:"1440";s:11:"enableBELog";s:1:"1";s:15:"showSampleTasks";s:1:"1";s:11:"useAtdaemon";s:1:"0";}',
			'simulatestatic' => 'a:0:{}',
			'version' => 'a:0:{}',
			'vhs' => 'a:0:{}',
			'workspaces' => 'a:0:{}',
		),
	),
	'EXTCONF' => array(
		'lang' => array(
			'availableLanguages' => array(
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'de',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
			),
		),
	),
	'FE' => array(
		'debug' => '',
	),
	'GFX' => array(
		'colorspace' => 'RGB',
		'im' => '1',
		'im_mask_temp_ext_gif' => '1',
		'im_path' => '/usr/bin/',
		'im_path_lzw' => '/usr/bin/',
		'im_v5effects' => '0',
		'im_version_5' => 'im6',
		'image_processing' => '1',
	),
	'INSTALL' => array(
		'wizardDone' => array(
			'TYPO3\CMS\Install\CoreUpdates\InstallSysExtsUpdate' => '["info","perm","func","filelist","about","cshmanual","feedit","opendocs","recycler","t3editor","reports","scheduler","simulatestatic"]',
			'TYPO3\CMS\Install\Updates\FileIdentifierHashUpdate' => 1,
			'TYPO3\CMS\Install\Updates\TceformsUpdateWizard' => 'tt_content:image,pages:media,pages_language_overlay:media',
			'TYPO3\CMS\Install\Updates\TruncateSysFileProcessedFileTable' => 1,
		),
	),
	'SYS' => array(
		'compat_version' => '6.2',
		'devIPmask' => '127.0.0.1,::1',
		'displayErrors' => '-1',
		'enableDeprecationLog' => '',
		'encryptionKey' => 'ec5f3597ad541a4c79523f8d98c1aa85d28ae5d97114f8b33b486cbb788d4619f0cc0f73ed6dd0f33557114111f2d884',
		'sitename' => '<%= websiteName %>',
		'sqlDebug' => '0',
		'systemLogLevel' => '0',
	),
);
?>