$ProjectName = '<%= _.slugify(websiteName) %>'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.hostname = "#{$ProjectName}"
  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.network :forwarded_port, guest: 3306, host: 33060
  config.vm.network :private_network, ip: "10.0.0.10"
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 2
  end

  config.vm.provision :shell, path: "bootstrap.sh"

end
